export const MAID_LIST_REQUEST = 'MAID_LIST_REQUEST'
export const MAID_LIST_SUCCESS = 'MAID_LIST_SUCCESS'
export const MAID_LIST_FAIL = 'MAID_LIST_FAIL'

export const MAID_DETAILS_REQUEST = 'MAID_DETAILS_REQUEST'
export const MAID_DETAILS_SUCCESS = 'MAID_DETAILS_SUCCESS'
export const MAID_DETAILS_FAIL = 'MAID_DETAILS_FAIL'